### PR TITLE
Version upgrade: Scala 2.13.0-RC3

### PR DESCRIPTION
**Pull request by dejan2609**
details:
- Scala:    2.13.0-RC2 -->> 2.13.0-RC3
- mockito-scala: 1.4.6 -->> 1.5.0 https://github.com/mockito/mockito-scala/blob/v1.5.0/docs/release-notes.md
- scalatest: 3.0.8-RC4 -->> 3.0.8-RC5

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @dejan2609,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by dejan2609** [comment]
Ok, I guess I will try to sign, scan and send individual CLA.

**Comment by TimMoore** [comment]
@dejan2609 you are certainly welcome to print and sign the CLA if you prefer to do it that way, but for our purposes, all that's needed is to authenticate by clicking the "Confirm with your GitHub account" if you and your employer agree to the terms.

**Comment by dejan2609** [comment]
@TimMoore done, thanx for the tip  !

**Comment by analytically** [comment]
Publishing scala-logging_2.13.0-RC3-3.9.2

**Pull request merged**
