### PR TITLE
Update scala 2.13.0-M5 to 2.13.0-RC1

### PR DESCRIPTION
**Pull request by Philippus**

### CODE REVIEW

**Comment by Philippus** [comment]
Build fails on #157

**Comment by Philippus** [comment]
@analytically can you have a look? I'd be happy to make some changes, but I'm not sure what would be the best ones. :)

**Comment by analytically** [comment]
Seems like a regression in RC1?

both method error in trait Logger of type (x$1: String, x$2: Object*)Unit
[error] and  method error in trait Logger of type (x$1: String, x$2: Any)Unit

**Comment by SethTisue** [comment]
I think https://github.com/scala/scala/pull/7631 might be relevant here?

**Comment by ijuma** [comment]
Do we get to a conclusion on how to proceed here? Is it a bug in Scala that will be fixed in RC2 or does scalalogging have to be updated?

**Comment by analytically** [comment]
I'd happily accept any PR that would fix scala-logging for 2.13.0-RC1, but IMO this is a regression.

**Comment by SethTisue** [comment]
if you (or anyone watching this ticket) thinks there is a bug in Scala, please open a ticket at https://github.com/scala/bug

**Comment by SethTisue** [comment]
https://github.com/scala/scala/pull/7680 seems also relevant

**Comment by SethTisue** [comment]
in order to get scala-logging green in the Scala community build, @adriaanm did a series of commits at https://github.com/scalacommunitybuild/scala-logging/commits/community-build-2.13

the relevant commit appears to be https://github.com/scalacommunitybuild/scala-logging/commit/650bed8a0bc99421d16e6c9059d3655aaee532e4

@Philippus does that give you what you need to update this PR for RC2...?

**Comment by SethTisue** [comment]
Adriaan's commit shows how to force the varargs version to be chosen. @dwijnand notes that ascribing `: Any` forces the other overload to be chosen:

```
scala 2.13.0-RC2> class Logger { def error(x: String, xs: AnyRef*) = 1; def error(x: String, x2: Any) = 2 }
defined class Logger

scala 2.13.0-RC2> (new Logger).error("a", "b")
                               ^
                  error: ambiguous reference to overloaded definition,
                  both method error in class Logger of type (x: String, x2: Any)Int
                  and  method error in class Logger of type (x: String, xs: AnyRef*)Int
                  match argument types (String,String)

scala 2.13.0-RC2> (new Logger).error("a", "b": Any)
res1: Int = 2
```

**Comment by SethTisue** [comment]
@Philippus if you run into any further trouble, scala/scala#7966 and scala/scala#8049 are also potentially relevant (thx @dwijnand)

**Comment by dwijnand** [comment]
In Java it works, and it uses the non-varargs (which is the same as type-ascribing with `Any`, and the opposite to what Scala 2.12 and Dotty do):

```java
19:23:28 $ JAVA_HOME=$(/usr/libexec/java_home -v 11) jshell
|  Welcome to JShell -- Version 11.0.2
|  For an introduction type: /help intro

jshell> class Logger { int error(String x, String... xs) { return 1; }; int error(String x, Object x2) { return 2; } }
|  created class Logger

jshell> (new Logger()).error("a", "b")
$2 ==> 2
```

**Comment by dwijnand** [comment]
Actually, I think this was fixed in RC2 (see those PRs).  Trying to recreate in the shell using 2.13.0-RC2 it seems all fine:

```scala
Welcome to Scala 2.13.0-RC2 (OpenJDK GraalVM CE 19.0.0, Java 1.8.0_212).
Type in expressions for evaluation. Or try :help.

scala> final class Logger { def error(message: String, cause: Throwable) = "throwable"; def error(message: String, args: Any*) = "varargs" }
defined class Logger

scala> (new Logger).error("a", new Error)
res0: String = throwable

scala> (new Logger).error("a", "b")
res1: String = varargs
```

**Comment by adriaanm** [comment]
Quick other correction to another issue I “fixed” in that branch: the
string interpolation interception macro needs to look at the expandee
attachment (HT retronym) to see the original string written by the
programmer, since the s interpolator is now a macro. I fixed this pretty
crudely by providing a local version of stringcontext, just to get those
tests to pass...

**Comment by adriaanm** [comment]
Let's continue the discussion at #162, where I hope we'll have a green upgrade to RC2 (tests pass for me locally).

**Pull request closed without merging**
