### PR TITLE
Update to Scala 3.0.0-RC3

### PR DESCRIPTION
**Pull request by bplommer**
By the way, it seems there hasn't been a release for Scala 3.0.0-RC2.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @bplommer,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Review by SethTisue — APPROVED** [review]

**Comment by flomebul** [comment]
Hello, while waiting for a new release for 3.0.0-RC2 and RC3, I discover that "scaladex" found "emoji" releases inside of "scala-logging"! Curious...
Otherwise, very happy that this new release will come soon 👍

**Comment by francisdb** [comment]
What is this PR waiting for?

**Comment by SethTisue** [comment]
> Hello, while waiting for a new release for 3.0.0-RC2 and RC3, I discover that "scaladex" found "emoji" releases inside of "scala-logging"! Curious...

Haha oh no... copy and paste gone awry... fix: https://github.com/lightbend/lightbend-emoji/pull/129

**Pull request merged**
