### PR TITLE
upgrade to Scala 2.11.12 and 2.13.0-M3, sbt 1.1.1

### PR DESCRIPTION
**Pull request by SethTisue**
once this has been merged, it would be nice if the library
were actually published for 2.13.0-M3, too

### CODE REVIEW

**Comment by sullis** [comment]
👍

**Comment by SethTisue** [comment]
this transitively blocking cats, via https://github.com/scoverage/scalac-scoverage-plugin/issues/214

**Comment by dwijnand** [comment]
Paging @analytically, kindly.

**Comment by analytically** [comment]
I'd love to merge but my rights on the repo are gone. @ktoso mind having a look, thanks.

**Comment by ktoso** [comment]
Sorry about that, seems the move dropped it... you're admin powers now

**Comment by SethTisue** [comment]
thanks @analytically! scala/make-release-notes@f8b3273189315409fe8538c0851fc5133e9dea6c

**Pull request merged**
